### ISSUE TITLE
Estilo de la página

### ISSUE THREAD

**Issue by zeratulmdq** [UTN-MDP/utn-chat#3]
Una vez resuelto #1 debe crearse una hoja de estilos para mejorar la visual de la página. El cuadro de texto y el botón _Enviar_ deben quedar fijos sobre la parte inferior, los mensajes deben diferenciar en tamaño/color el emisor y el contenido del mismo, sobre la parte superior debe aparecer algún indicador del usuario y lo que sea que se utilice para cambiar el nombre de usuario queda a criterio del creador del PR.

**Comment by zeratulmdq** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Chat - Estilos](https://trello.com/c/ohouZfBk/12-chat-estilos)

**Comment by co0per** [comment]
canto este

**Comment by zeratulmdq** [comment]
Cerrado por #6
